# Generated by Django 3.1.2 on 2021-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=2048)),
                ('linkedin', models.URLField(max_length=2048)),
                ('twitter', models.URLField(max_length=2048)),
                ('facebook', models.URLField(max_length=2048)),
                ('post_date', models.CharField(max_length=100)),
            ],
        ),
    ]
