# Generated by Django 3.1.2 on 2021-10-05 17:19

import django.core.validators
import djongo.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('email_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='BDEventID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='business_category',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.CharField(blank=True, choices=[('Trade_show', 'Trade show'), ('Webinar', 'Webinar'),
                                                        ('Conference', 'Conference')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='exhibitor_creator_list',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='exhibitor_form',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='exhibitor_list',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='exhibitors_number',
            field=models.IntegerField(blank=True, null=True,
                                      validators=[django.core.validators.MaxValueValidator(99999),
                                                  django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='event',
            name='hashtag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=djongo.storage.GridFSStorage(
                base_url='https://100043.pythonanywhere.com/media/', collection='newspaper'), upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='mention',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='opportunities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser_website',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='promotion',
            field=models.CharField(blank=True, choices=[('Mail', 'Mail only'), ('Offline', 'Offline only'),
                                                        ('Online', 'Online only'), ('No', 'No'), ('Hybrid', 'Hybrid')],
                                   max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True,
                                   choices=[('Complete', 'Complete'), ('InProgress', 'InProgress'), ('Error', 'Error')],
                                   max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tagline',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tiktok',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Offline', 'Offline only'), ('Online', 'Online only'),
                                                        ('Hybrid', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vanue_page_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_website',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='visitors_number',
            field=models.IntegerField(blank=True, null=True,
                                      validators=[django.core.validators.MaxValueValidator(99999),
                                                  django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
