# Generated by Django 3.1.2 on 2021-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('email_parser', '0002_auto_20211005_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(blank=True, choices=[('Trade_show', 'Trade show'), ('Webinar', 'Webinar'),
                                                        ('Conference', 'Conference')], max_length=30, null=True),
        ),
    ]
