# Generated by Django 4.1.10 on 2023-07-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "_id",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("Timestamp", models.DateTimeField()),
                ("Email_Address", models.EmailField(max_length=254)),
                ("exhibitor_name", models.CharField(max_length=100)),
                ("brand_name", models.CharField(max_length=100)),
                ("person_incharge", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("exhibitor_page", models.URLField()),
                ("website", models.URLField()),
                ("email_exhibitor", models.EmailField(max_length=254)),
                ("booth_number", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("exhibitor_type", models.CharField(max_length=100)),
                ("products", models.TextField()),
                ("linkedin", models.URLField()),
                ("twitter", models.URLField()),
                ("facebook", models.URLField()),
                ("instagram", models.URLField()),
                ("youtube", models.URLField()),
                ("tiktock", models.URLField()),
                ("hashtag", models.TextField()),
                ("mention", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("Logo", models.BinaryField()),
            ],
        ),
    ]
