# Generated by Django 3.1.2 on 2021-10-07 06:41

import djongo.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0003_auto_20211005_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='logo',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(base_url='form.urlsmedia/', collection='fs'),
                                    upload_to=''),
        ),
    ]
