# Generated by Django 3.1.2 on 2021-10-18 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0005_auto_20211007_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
