# Generated by Django 3.1.2 on 2021-10-18 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exhibitors', '0005_exhibitor_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
